name: Fetch and push data

on:
  schedule:
    - cron: "1 3 * * 1-5" # 12:01 in UTC+9
    - cron: "11 3 * * 1-5" # 12:11 in UTC+9

jobs:
  fetch_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
      - uses: actions/checkout@v1
      - run: go run main.go
      - run: |
          (grep $(TZ='Asia/Tokyo' date '+%Y-%m-%d') holidays.txt > /dev/null) && exit 0 # skip holidays
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add public/ result/
          git commit -m "Update $(date '+%Y-%m-%d')" || exit 0
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
